default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  host: localhost
  username: postgres
  password:
  database: sispict_development
test:
  <<: *default
  host: localhost
  username: postgres
  password:
  database: sispict_test
production:
  <<: *default
  host: localhost
  database: sispict_production
  username: sispict
  password: <%= ENV['SISPICT_DATABASE_PASSWORD'] %>
