# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b761d0a33232fa3c316d4eb3cfd8425f7318d8bec47f57f22c234d1b64bda2ef57b4a445792b8db417d2d828ecc20ddf69fab3cc01926f5b75f3d4bbc16f8c25

test:
  secret_key_base: 4a5d1e032b9c472abc09797ba7555e5445ec8c9662a96e6f282221fd07385d0734f7dbe8cec7f0f6b3d0a04418573f64ebd7a989e297f6150df45c475df15f1d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
